# Generated by Django 5.2.7 on 2025-10-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screener', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('company', 'Company')], default='candidate', max_length=20),
        ),
    ]
