# Generated by Django 5.2.7 on 2025-11-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screener', '0004_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
