# Generated by Django 5.2.7 on 2025-11-15 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screener', '0006_alter_profile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='whatsapp_number',
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_job', models.CharField(max_length=100)),
                ('preferred_location', models.CharField(max_length=100)),
                ('skills', models.TextField(blank=True, null=True)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Screener.profile')),
            ],
        ),
    ]
