# Generated by Django 5.2.7 on 2025-11-15 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Screener', '0007_remove_profile_full_name_remove_profile_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='preferred_job',
        ),
    ]
