# Generated by Django 5.2.7 on 2025-11-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screener', '0008_remove_candidates_preferred_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='candidates',
            name='work_type',
            field=models.CharField(choices=[('wfh', 'Work From Home'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], default='onsite', max_length=10),
        ),
    ]
