# Generated by Django 5.2.7 on 2025-11-15 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screener', '0009_candidates_gender_candidates_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_details', to='Screener.profile'),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='work_type',
            field=models.CharField(choices=[('wfh', 'Work From Home'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], max_length=10),
        ),
    ]
