# Generated by Django 5.2.7 on 2025-11-25 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screener', '0010_alter_candidates_gender_alter_candidates_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Screener.profile'),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='work_type',
            field=models.CharField(choices=[('wfh', 'Work From Home'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], default='onsite', max_length=10),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logos/')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, max_length=300, null=True)),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.CharField(blank=True, choices=[('1-10 employees', '1-10 employees'), ('10-50 employees', '10-50 employees'), ('50-200 employees', '50-200 employees'), ('200-500 employees', '200-500 employees'), ('500+ employees', '500+ employees')], max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=300, null=True)),
                ('twitter', models.URLField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
