# Generated by Django 5.2.7 on 2025-11-25 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screener', '0011_alter_candidates_gender_alter_candidates_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Screener.profile'),
        ),
    ]
