# Generated by Django 5.2.7 on 2025-11-26 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screener', '0012_alter_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(choices=[('Remote', 'Remote'), ('Office', 'On Site'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('job_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Internship', 'Internship'), ('Contract', 'Contract')], max_length=20)),
                ('experience_type', models.CharField(choices=[('Fresher', 'Fresher'), ('Experienced', 'Experienced Professional')], max_length=30)),
                ('min_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('max_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('min_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('max_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('skills', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Screener.company')),
            ],
        ),
    ]
