# Generated by Django 5.2.7 on 2025-11-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screener', '0013_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='Active', max_length=20),
        ),
    ]
