# Generated by Django 5.2.7 on 2025-11-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screener', '0014_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20),
        ),
    ]
